grpc.server.port=${TX_MANAGER_PORT}
cdb.chronicle.service.ip=${CHRONICLE_SERVICE_IP}
cdb.chronicle.service.port=${CHRONICLE_SERVICE_PORT}
chronicle-id=${CHRONICLE_ID}
write-schema-json=${WRITE_SCHEMA_JSON}